// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestOlympe_Server.Data;

#nullable disable

namespace RestOlympe_Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240505154944_AddFieldConstraints")]
    partial class AddFieldConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.LobbyModel", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<float>("VoteRadiusKm")
                        .HasColumnType("real");

                    b.HasKey("LobbyId");

                    b.HasIndex("AdminId");

                    b.ToTable("lobbies", (string)null);
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("lobby_user", b =>
                {
                    b.Property<Guid>("LobbiesAsUserLobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersUserId")
                        .HasColumnType("uuid");

                    b.HasKey("LobbiesAsUserLobbyId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("lobby_user");
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.LobbyModel", b =>
                {
                    b.HasOne("RestOlympe_Server.Models.Entities.UserModel", "Admin")
                        .WithMany("LobbiesAsAdmin")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("lobby_user", b =>
                {
                    b.HasOne("RestOlympe_Server.Models.Entities.LobbyModel", null)
                        .WithMany()
                        .HasForeignKey("LobbiesAsUserLobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestOlympe_Server.Models.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.UserModel", b =>
                {
                    b.Navigation("LobbiesAsAdmin");
                });
#pragma warning restore 612, 618
        }
    }
}
