// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestOlympe_Server.Data;

#nullable disable

namespace RestOlympe_Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240604093402_UpdateRadiusType")]
    partial class UpdateRadiusType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.LobbyModel", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("VoteRadiusKm")
                        .HasColumnType("bigint");

                    b.HasKey("LobbyId");

                    b.HasIndex("AdminId");

                    b.ToTable("lobbies", (string)null);
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.VoteModel", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("OsmId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("LobbyId", "UserId", "OsmId");

                    b.HasIndex("UserId");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("lobby_user", b =>
                {
                    b.Property<Guid>("LobbiesAsUserLobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersUserId")
                        .HasColumnType("uuid");

                    b.HasKey("LobbiesAsUserLobbyId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("lobby_user");
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.LobbyModel", b =>
                {
                    b.HasOne("RestOlympe_Server.Models.Entities.UserModel", "Admin")
                        .WithMany("LobbiesAsAdmin")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.VoteModel", b =>
                {
                    b.HasOne("RestOlympe_Server.Models.Entities.LobbyModel", "Lobby")
                        .WithMany("Votes")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestOlympe_Server.Models.Entities.UserModel", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("lobby_user", b =>
                {
                    b.HasOne("RestOlympe_Server.Models.Entities.LobbyModel", null)
                        .WithMany()
                        .HasForeignKey("LobbiesAsUserLobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestOlympe_Server.Models.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.LobbyModel", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("RestOlympe_Server.Models.Entities.UserModel", b =>
                {
                    b.Navigation("LobbiesAsAdmin");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
